### ISSUE TITLE
pod中的多个容器的启动顺序

### ISSUE THREAD

**Issue by jamesalice123** [rootsongjc/kubernetes-handbook#197]
## 环境
centos7.4
**版本和配置信息**

- kubernetes版本：1.7
- docker版本：1.13.1
- 网络插件：calico
- 存储类型：

## 操作  kubectl apply -f wm-application1.yaml

**导致该问题的操作或现象**
[root@k8s-1 ~]# cat wm-apployment1.yaml 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: wm-application1
spec:
  containers:
  - name: wm-govern
    image: 139.219.69.45:8060/library/wm-govern
    command:["sleep 60"]
    resources:
      requests:
        memory: "1Gi"
      limits:
        memory: "1.5Gi"
  - name: wm-configserver
    image: 139.219.69.45:8060/library/wm-configserver
    command:["sleep 90"]
    resources:
      requests:
        memory: "1Gi"
      limits:
        memory: "1.5Gi"
  - name: goods-management
    image: 139.219.69.45:8060/library/goods-management
    resources:
      requests:
        memory: "1Gi"
      limits:
        memory: "1.5Gi"
```
==========================================================================
```bash
[root@linqiuhua image]# cat Dockerfile 
from java:8
add  wm-configserver-1.0.1.jar  /
volume /data
cmd java -jar/wm-configserver-1.0.1.jar
```
## 日志　　容器启动失败  

**日志或报错信息**　　　

问题：　yaml文件中的command命令和dockerfile文件中的cmd命令该如何定义呢，
command: [String]     //容器的启动命令列表（不配置的话使用镜像内部的命令）不太明白这句话，
我的需求是pod中的多个容器之间的执行需要间隔一段时间。

**Comment by whmzsu** [comment]
command: [String] //容器的启动命令列表（不配置的话使用镜像内部的命令）不太明白这句话

就是pod文件的command命令可以覆盖容器内部的命令，你的例子就是["sleep 60"]  覆盖了cmd java -jar/wm-configserver-1.0.1.jar，容器内部命令不会被执行。所以你的容器应该是sleep 跑完以后就退出了，因为没有前台进程了。当前Kubernetes好像对pod内部容器的启动顺序还没有定义，除了init容器。

**Comment by rootsongjc** [comment]
Kuberentes 的 YAML 中定义的 command 会直接覆盖 Dockerfile 中的 CMD 和 Entrypoint，如果 YAML 中只写 args 则会将参数传递到 Dockerfile 中的 CMD。command 与容器的启动顺序没关系。

**Comment by jamesalice123** [comment]
@whmzsu　pod中的容器需要时间间隔的启动顺序而且又不能退出，那这样的话，我的只能把这些容器分开放到每个pod中，一个一个启动pod来控制时间顺序了，是吗

**Comment by whmzsu** [comment]
如果用分开放到不同POD方法，手动控制启动顺序是可以的，但是这样做不是很方便。
用sleep时间来控制容器进程的时间不是很可靠，因为POD里面容器起来的时间包括镜像下载的时间。如果镜像是在你的环境本地，启动时间比较可靠的话，你可以稍微改下需要延迟启动的容器的cmd命令，比如把command:["sleep 60"]改成command:["sleep 60 && java -jar/wm-configserver-1.0.1.jar"]。

**Comment by jamesalice123** [comment]
[root@k8s-2 data]# docker run -d 139.219.69.45:8060/library/wm-govern:1 --name=wm
3cfd8f2ffc8f0708348f8a1e29cc1225a9fea417782c95699c2130b581be160a
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"--name=wm\": executable file not found in $PATH".

请问我制作的镜像cmd执行是不是不对，哪里出了问题呢

==============================================================================
from java:8
add  wm-govern-1.0.1.jar  /
volume /data
cmd java -jar/wm-govern-1.0.1.jar

**Comment by jamesalice123** [comment]
@whmzsu [root@k8s-2 data]# docker run -d 139.219.69.45:8060/library/wm-govern:1 --name=wm
3cfd8f2ffc8f0708348f8a1e29cc1225a9fea417782c95699c2130b581be160a
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: "--name=wm": executable file not found in $PATH".

请问我制作的镜像cmd执行是不是不对，哪里出了问题呢

==============================================================================
from java:8
add wm-govern-1.0.1.jar /
volume /data
cmd java -jar/wm-govern-1.0.1.jar

**Comment by whmzsu** [comment]
镜像里有打包java环境吗？？？？或者把java命令的绝对路径给加上

**Comment by jamesalice123** [comment]
@whmzsu ["sleep 60 && java -jar/wm-configserver-1.0.1.jar"]这个方法不行

**Comment by whmzsu** [comment]
把错误日志贴出来看看

**Comment by jamesalice123** [comment]
@whmzsu [root@linqiuhua image]#  docker run --name "test33" -d  139.219.69.45:8060/library/wm-govern:33
10c5577544da5e3f56d784c6bdf3cf63d1fe7e0ae2aebb5b67446f6067cc0215
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"java -jar/wm-govern-1.0.1.jar && sleep 60\": stat java -jar/wm-govern-1.0.1.jar && sleep 60: no such file or directory".
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
[root@linqiuhua image]# cat Dockerfile 
from java:8
add  wm-configserver-1.0.1.jar  /
volume /data
cmd java -jar/wm-configserver-1.0.1.jar
使用　　docker run --name "test"  -d 139.219.69.45:8060/library/wm-configserver:v1.1 
可以启动，没有错误，但是docker ps -a 查看的时候，容器退出了，不知道为什么

**Comment by jamesalice123** [comment]
是的，镜像那边的问题做好了，但是主要的问题容器启动顺序还是没有思路，刚才您说的probe，我去看了一下他是一个健康机制，跟我这个应用的启动似乎关联不起来。我的java程序之间的启动需要等待一段时间才能启动另一个的，所以我需要时间顺序的

**Comment by whmzsu** [comment]
上面已经说过了，在一个pod内控制容器启动顺序的机制当前应该还没有。所以建议分开POD，然后在各个需要延迟业务启动的POD里面用init容器来检测其他服务是否准备完毕。

**Comment by rootsongjc** [comment]
可以结合probe来做，参考该示例：[zookeeper.yaml](https://github.com/rootsongjc/kubernetes-handbook/blob/master/manifests/zookeeper/zookeeper.yaml)。
下面是截取的片段。
```yaml
        command:
        - sh
        - -c
        - zkGenConfig.sh && zkServer.sh start-foreground
        readinessProbe:
          exec:
            command:
            - "zkOk.sh"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - "zkOk.sh"
          initialDelaySeconds: 10
          timeoutSeconds: 5
```
如果健康检查失败容器会自动重启，这样你也不用关心到底哪个容器先启动了，只要保证最后Pod中两个容器都是健康并就绪就可以了。与原先镜像唯一的不同可能就是要在原先的Docker容器中增加一个检测脚本。
