### ISSUE TITLE
按照安装文档部署的k8s集群，kube-proxy nodeport形式不能绑定配置的ip

### ISSUE THREAD

**Issue by kinglion811** [rootsongjc/kubernetes-handbook#202]
## 环境

**版本和配置信息**

- kubernetes版本：
v1.10
- docker版本：
docker-ce-1.17.2
- 网络插件：
flannel

## 操作
部署dashboard 采用nodeport 形式
```yaml
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 30002
```
kube-proxy 配置`--bind-address=10.48.144.28 --hostname-override=10.48.144.28`

**导致该问题的操作或现象**

为什么，执行 netstat -ntlp  查看端口占用情况 没有绑定ip 还是使用ipv6

![image](https://user-images.githubusercontent.com/6119243/39241703-6a518a72-48ba-11e8-895f-1c4efa4364f3.png)

## 日志

**日志或报错信息**
