### ISSUE TITLE
service访问pod没有回应，master直接访问容器也没有回应

### ISSUE THREAD

**Issue by jamesalice123** [rootsongjc/kubernetes-handbook#204]
## 环境
centos7
**版本和配置信息**

- kubernetes版本：1.7
- docker版本：1.13.1
- 网络插件：calico
- 存储类型：

## 操作
[root@k8s-1 ~]# curl 10.96.68.105:8080

[root@k8s-1 ~]# curl 192.168.200.233

**导致该问题的操作或现象**

```
[root@k8s-1 ~]# cat test.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas:
  template:
    metadata:
      labels:
        run: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 5000
      nodeSelector:
        disktype: ssd22
```
=========================================
```
[root@k8s-1 ~]# cat test-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    run: httpd
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 5000
  externalIPs:
    - 40.125.204.113
```
问题：我想测试使用外网ip 作为externalIPs是否和service的ip 一样可以外部访问pod ,但结果是都没有回应，不知道哪里错了

## 日志

**日志或报错信息**

没有回应，应该出现的结果是返回　
```
<html><body><h1>It   works!</h1></body></html>
```
