### ISSUE TITLE
glusterfs 做持久存储的问题

### ISSUE THREAD

**Issue by songhe2136** [rootsongjc/kubernetes-handbook#288]
老师：我现在用gluster 做 storageclass 动态pv。 heketi 管理 gluster 的 volume。   但是这种方式并不能创建 分布式复制卷，glusterfs 生产一般不是用 分布式复制卷吗。  用heketi 不支持这种卷类型，是我搞错了吗？

**Comment by rootsongjc** [comment]
你好，glusterfs我没有仔细研究过，希望有人可以给你解答。

**Comment by songhe2136** [comment]
好的，谢谢！

**Comment by fkpwolf** [comment]
https://github.com/heketi/heketi/blob/master/docs/api/api.md#create-a-volume 如果设置 type: replicate 不就是分布式卷了么？

**Comment by rockwyc992** [comment]
可以參考以下的 yaml 去設置你的 heketi 策略
``` yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gfs-disperse
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "https://heketi.example.com"
  volumetype: disperse:2:1
```
