### ISSUE TITLE
"安装kubedns插件"文档中有一处linux操作命令有误

### ISSUE THREAD

**Issue by Paul-Xiong** [rootsongjc/kubernetes-handbook#306]
## 环境

**版本和配置信息**

- kubernetes版本：
- docker版本：
- 网络插件：
- 存储类型：

## 操作

**导致该问题的操作或现象**

问题描述：在"安装kubedns插件"的文档中，有处linux操作貌似有误，问题截图如下：

![image](https://user-images.githubusercontent.com/16216658/48055305-428e0280-e1ea-11e8-8347-fd3db4ab985c.png)

有效操作如下：

```
cat >> my-nginx.yaml << EOF
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: harbor-001.jimmysong.io/library/nginx:1.9
        ports:
        - containerPort: 80
EOF
```

望采纳

## 日志

**日志或报错信息**
