### ISSUE TITLE
command traefik error: flag needs an argument: -kubernetes

### ISSUE THREAD

**Issue by emg2012-emg** [rootsongjc/kubernetes-handbook#380]
## 环境

**版本和配置信息**
```
[root@master1 traefik]# cat traefik-ingress-lb.yaml 
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-lb
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      restartPolicy: Always
      serviceAccountName: traefik-ingress
      containers:
      - image: 192.168.0.161/eloancn-test/traefik
        imagePullPolicy: IfNotPresent
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8580
          hostPort: 8580
        args:
        - --web
        - --web.address=:8580
        - --kubernetes
      nodeSelector:
        edgenode: "true
```
- kubernetes版本：v1.4.6
- docker版本：18.09.6
- 网络插件：flannel
- 存储类型：

## 操作
部署traefik pod无法启动
**导致该问题的操作或现象**

## 日志

**日志或报错信息**

2019/10/28 08:41:30 command traefik error: flag needs an argument: -kubernetes
