### ISSUE TITLE
在Kubernetes中使用Glusterfs做持久化存储访问不了glusterfs

### ISSUE THREAD

**Issue by ZhengRongTan** [rootsongjc/kubernetes-handbook#49]
修改 endpoints.json ，配置 glusters 集群节点ip
每一个 addresses 为一个 ip 组
```
    {
      "addresses": [
        {
          "ip": "172.22.0.113"
        }
      ],
      "ports": [
        {
          "port": 1990
        }
      ]
    },
```
**导入 glusterfs-endpoints.json**
```
$ kubectl apply -f glusterfs-endpoints.json
```
**查看 endpoints 信息**
```
$ kubectl get ep
```
 

我想问的是这里的1990端口是随机的吗？ 为什么我在配置1990或默认1端口，都会报错,报错内容：

```
MountVolume:NewMounter initialization failed for volume "glusterfsvol": endpoints "glusterfs-cluster" not found;
```

我的配置如下：
```
[root@CNSZ22PL1265 glusterfs]# cat gluster-ep.yaml 
apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-cluster
  namespace: kube-system
subsets:
- addresses:              
  - ip: 10.202.77.200
  ports:                  
  - port: 1
    protocol: TCP
- addresses:
  - ip: 10.202.77.201
  ports:
  - port: 1
    protocol: TCP
- addresses:
  - ip: 10.202.77.202
  ports:
  - port: 1
    protocol: TCP
```
```
[root@CNSZ22PL1265 glusterfs]# cat gluster-svc.yaml 
apiVersion: v1
kind: Service
metadata:
  name: gluster-cluster
  namespace: kube-system
spec:
  ports:
  - port: 1
```
```
[root@CNSZ22PL1265 glusterfs]# gluster volume info
 
Volume Name: es-volume
Type: Distribute
Volume ID: 364f5bc8-672c-4002-b454-89ef729064cc
Status: Started
Snapshot Count: 0
Number of Bricks: 3
Transport-type: tcp
Bricks:
Brick1: 10.202.77.200:/DATA/glusterfs/esdata
Brick2: 10.202.77.201:/DATA/glusterfs/esdata
Brick3: 10.202.77.202:/DATA/glusterfs/esdata
Options Reconfigured:
performance.write-behind: on
performance.io-thread-count: 64
performance.flush-behind: on
performance.cache-size: 16GB
features.quota-deem-statfs: on
features.inode-quota: on
features.quota: on
transport.address-family: inet
nfs.disable: on
```

pod配置如下：
```
[root@CNSZ22PL1265 glusterfs]# cat busybox-pod.yaml
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "name": "glusterfs",
        "namespace": "kube-system"
    },
    "spec": {
        "containers": [
            {
                "name": "glusterfs",
                "image": "busybox",
                "volumeMounts": [
                    {
                        "mountPath": "/mnt/glusterfs",
                        "name": "glusterfsvol"
                    }
                ]
            }
        ],
        "volumes": [
            {
                "name": "glusterfsvol",
                "glusterfs": {
                    "endpoints": "glusterfs-cluster",
                    "path": "es-volume",
                    "readOnly": false
                }
            }
        ]
    }
}
```
