### ISSUE TITLE
StatefulSet中serviceName的疑问

### ISSUE THREAD

**Issue by sxauyhz** [rootsongjc/kubernetes-handbook#53]
你好，麻烦咨询个问题，创建StatefulSet之前创建个headless service时必须的吗？即如下配置中serviceName的作用是关联service还是可以随便指定？该选项是必须的吗？
```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
...
```
