### ISSUE TITLE
代码与镜像分离-使用外部挂载应用代码启动应用

### ISSUE THREAD

**Issue by rootsongjc** [rootsongjc/kubernetes-handbook#55]
## 需求
搞个镜像,可以运行`java -jar xxx.jar`包,xxx.jar包名称要用参数传

- 思路1: 打对应运行jar包的jdk的镜像
- 思路2: 打通用jdk镜像

## 1. 运行指定jar的指定版的jdk
**k8s运行该image遇到的问题**

`kubectl create -f sms.yaml`时报：

```
  rpc error: code = 2 desc = failed to start container "cffbbc3d295f7b5a8d497c8147f7222636b51647387cda491a89d292437c7e47": Error response from daemon: {"message":"invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"exec: \\\\\\\"/tmp/sms-xx.jar\\\\\\\": permission denied\\\"\\n\""} 
```
等了一会pod崩溃了，报错：

```  
  failed to open log file "/var/log/pods/6533426e-aeec-11e7-b1c6-025622f1d9fa/sms-test_3.log": open /var/log/pods/6533426e-aeec-11e7-b1c6-025622f1d9fa/sms-test_3.log: no such file or directory 
```
Google了好一阵，没发现方法解决。

**这是我的yaml**

sms.yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sms-test
  labels:
    app: sms-test
spec:
  containers:    
  - name: sms-test
    image: sms
    imagePullPolicy: IfNotPresent
    command: ["/tmp/sms-xxx.jar"]
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /tmp
```
报错问题见上!

---
- 但是我这样启镜像是正常的
```bash
#vm的tmp下放xxx.jar,挂到容器里
docker run -v /tmp:/tmp -itd sms '/tmp/sms-xxx.jar'
```
我一般处理容器化业务思路:

1. 物理vm先打通该服务
2. 打docker镜像
3. docker run先跑起来
4. 写yaml改造成k8s
---

我按照思路1定义运行jar包的jdk:的dockerfile

```dockerfile
FROM airdock/base:jessie

RUN mkdir -p /srv/java/
# Add java dynamic memory script
COPY java-dynamic-memory-opts /srv/java/

# Install Oracle JDK 8u25
RUN cd /tmp && \
    curl -L -O "http://xxx/jdk-8u25-linux-x64.gz" && \
    tar xf jdk-8u25-linux-x64.gz -C /srv/java && \
    rm -f jdk-8u25-linux-x64.gz && \
    ln -s /srv/java/jdk* /srv/java/jdk && \
    ln -s /srv/java/jdk /srv/java/jvm && \
    chown -R java:java /srv/java && \
    /root/post-install

# Define commonly used JAVA_HOME variable
# Add /srv/java and jdk on PATH variable
ENV JAVA_HOME=/srv/java/jdk \
    PATH=${PATH}:/srv/java/jdk/bin:/srv/java

COPY docker-entrypoint.sh /bin/
```

`docker-entrypoint.sh`

```bash
#!/bin/bash
java -jar $1
```
嗯哼? 没毛病。

## 解决k8s运行定制jdk环境的问题:
方法: yaml里command换args指令即可.

sms.yaml

```yaml
...
spec:
  containers:    
  - name: sms-test
    image: sms
    imagePullPolicy: IfNotPresent
    args: ["/tmp/sms-xxx.jar"]
...
```

**剖析**

```bash
docker run -v /tmp:/tmp -itd sms '/tmp/sms-xxx.jar'                                                        这里args,而非commands
```

## 2. 使jdk环境通用化
想想为了运行一个jar包，定义个运行jar的jdk环境,有点得不偿失。思路：为了通用性,搞个指定版本jdk image,管他运行什么呢。

Dockerfile如下：

```dockerfile
FROM airdock/base:jessie

RUN mkdir -p /srv/java/
# Add java dynamic memory script
COPY java-dynamic-memory-opts /srv/java/

# timezone 这里把时区改掉
COPY localtime /etc/localtime
# Install Oracle JDK 8u25
RUN cd /tmp && \
    curl -L -O "http://xxx/jdk-8u25-linux-x64.gz" && \
    tar xf jdk-8u25-linux-x64.gz -C /srv/java && \
    rm -f jdk-8u25-linux-x64.gz && \
    ln -s /srv/java/jdk* /srv/java/jdk && \
    ln -s /srv/java/jdk /srv/java/jvm && \
    chown -R java:java /srv/java && \
    /root/post-install

# Define commonly used JAVA_HOME variable
# Add /srv/java and jdk on PATH variable
ENV JAVA_HOME=/srv/java/jdk \
    PATH=${PATH}:/srv/java/jdk/bin:/srv/java
```

yaml配置如下：

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sms-test
  labels:
    app: sms-test
spec:
  containers:    
  - name: sms-test
    image: jdk8u25-ori
    imagePullPolicy: IfNotPresent
    command: ["java","-jar","/tmp/sms-xxx.jar"]
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /data
```
经过观察jar包运行良好。
可见理解k8s yaml指令还是有点必要的。不然天天闲的蛋疼，没事干。人生最大的敌人是无聊。
