### ISSUE TITLE
kubernetes-dashboard access failed

### ISSUE THREAD

**Issue by xyzsss** [rootsongjc/kubernetes-handbook#67]
### 环境： 
   `OS: CentOS7`
`#uname -a`
`Kernel:Linux k8node1 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
`# docker --version`
`Docker version 17.10.0-ce, build f4ffd25`
`#kubectl version`
`Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}`

`Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:24:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}`

### IP 信息
  10.0.15.111（node&&master）
  10.0.15.110（node）
  10.0.15.115（node）

### 防火墙设置(三个节点都一致)
```
#iptables -L FORWARD
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere 
```
### flanneld 服务(三个节点都一致)
```
systemctl  is-active flanneld  
active
```

### 服务状态
```
#kubectl get pods --namespace=kube-system
NAME                                    READY     STATUS    RESTARTS   AGE
kubernetes-dashboard-1454826952-hsk8b   1/1       Running   0          1h

#kubectl describe pods kubernetes-dashboard-1454826952-hsk8b  --namespace=kube-system
Name:		kubernetes-dashboard-1454826952-hsk8b
Namespace:	kube-system
Node:		10.0.15.115/10.0.15.115
Start Time:	Thu, 16 Nov 2017 16:15:34 +0800
Labels:		k8s-app=kubernetes-dashboard
		pod-template-hash=1454826952
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kubernetes-dashboard-1454826952","uid":"51ff9593-caa6-11e7-b...
		scheduler.alpha.kubernetes.io/critical-pod=
Status:		Running
IP:		172.17.0.3
Controllers:	ReplicaSet/kubernetes-dashboard-1454826952
Containers:
  kubernetes-dashboard:
    Container ID:	docker://fd08a23551ae24279ea68adcf59e3568c0cb2e73c293aee19fc58ae1cf15ef46
    Image:		10.0.15.166:5555/kubernetes-dashboard-amd64:v1.6.3
    Image ID:		docker-pullable://10.0.15.166:5555/kubernetes-dashboard-amd64@sha256:d820c9a0a0a7cd7d0c9d3630a2db0fc33d190db31f3e0797d4df9dc4a6a41c6b
    Port:		9090/TCP
    State:		Running
      Started:		Thu, 16 Nov 2017 16:15:35 +0800
    Ready:		True
    Restart Count:	0
    Limits:
      cpu:	100m
      memory:	50Mi
    Requests:
      cpu:		100m
      memory:		50Mi
    Liveness:		http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-f4z0c (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  default-token-f4z0c:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-f4z0c
    Optional:	false
QoS Class:	Guaranteed
Node-Selectors:	<none>
Tolerations:	CriticalAddonsOnly=:Exists
Events:		<none>

#kubectl logs kubernetes-dashboard-1454826952-hsk8b  -n kube-system
Using HTTP port: 8443
Using in-cluster config to connect to apiserver
Using service account token for csrf signing
No request provided. Skipping authorization header
Successful initial request to the apiserver, version: v1.6.0
No request provided. Skipping authorization header
Creating in-cluster Heapster client
Could not enable metric client: Health check failed: User "system:serviceaccount:kube-system:default" cannot proxy services in the namespace "kube-system". (get services heapster). Continuing.
```

## 问题  
通过设定  
```
#kubectl proxy --address='10.0.15.115' --port=8086 --accept-hosts='^*$'
Starting to serve on 10.0.15.115:8086
```
访问 http://10.0.15.115:8086/ui 时, 自动跳转到 http://10.0.15.115:8086/api/v1/namespaces/kube-system/services/-dashboard/proxy/  。
页面返回：  
```
Error: 'dial tcp 172.17.0.3:9090: getsockopt: no route to host'
Trying to reach: 'http://172.17.0.3:9090/'
```  
在 10.0.15.115（node） 上  
```
#ping 172.17.0.3
#curl 172.17.0.3:9090
 <!doctype html> <html ng-app="kubernetesDashboard"> <head> <meta charset="utf-8"> <title ng-controller="kdTitle as $ctrl" ng-bind="$ctrl.title()"></title> <link rel="icon" type="image/png" href="assets/images/kubernetes-logo.png"> <meta name="viewport" content="width=device-width"> <link rel="stylesheet" href="static/vendor.9aa0b786.css"> <link rel="stylesheet" href="static/app.8ebf2901.css"> </head> <body> <!--[if lt IE 10]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser.
      Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your
      experience.</p>
    <![endif]--> <kd-chrome layout="column" layout-fill> </kd-chrome> <script src="static/vendor.840e639c.js"></script> <script src="api/appConfig.json"></script> <script src="static/app.68d2caa2.js"></script> </body> </html> 
```
都能够得到结果

**在 10.0.15.115（node） 和 10.0.15.111（node&&master） 上都 `ping` 不通。**

尝试进入 dashboard 容器失败
```
#kubectl exec -it kubernetes-dashboard-1454826952-hsk8b  bash  -n kube-system
oci runtime error: exec failed: container_linux.go:295: starting container process caused "exec: \"bash\": executable file not found in $PATH"
```

相关 issue 并没有能解决问题：
 [通过kube-apiserver访问dashboard报错](https://github.com/opsnull/follow-me-install-kubernetes-cluster/issues/145)
[restart docker daemon is not work](https://github.com/kubernetes-graveyard/kube-ui/issues/8)

**Comment by rootsongjc** [comment]
能附上你的`dashboard`的yaml文件吗？可以直接使用`nodePort` service type来暴露服务啊，你检查过flannel网络是否有问题？kube-proxy日志有没有错误？

**Comment by xyzsss** [comment]
## dashboard 的 yaml 文件  

###  dashboard-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  type: NodePort
  selector:
    k8s-app: kubernetes-dashboard
  ports:
  - port: 80
    targetPort: 9090
```


### dashboard-rbac.yaml 
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
  namespace: kube-system

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dashboard
subjects:
  - kind: ServiceAccount
    name: dashboard
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```  


### dashboard-controller.yaml 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: kubernetes-dashboard
  template:
    metadata:
      labels:
        k8s-app: kubernetes-dashboard
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - name: kubernetes-dashboard
        #image: sz-pg-oam-docker-hub-001.tendcloud.com/library/kubernetes-dashboard-amd64:v1.6.3
        #image: kubernetes-dashboard-amd64:v1.6.3
        #image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0
        image: 10.0.15.166:5555/kubernetes-dashboard-amd64:v1.6.3
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
```


##  flannel网络是否有问题
```
#etcdctl --endpoints=${ETCD_ENDPOINTS} \
>   --ca-file=/etc/kubernetes/ssl/ca.pem \
>   --cert-file=/etc/kubernetes/ssl/kubernetes.pem \
>   --key-file=/etc/kubernetes/ssl/kubernetes-key.pem \
>   ls /kube-centos/network/subnets
2017-11-16 22:48:51.932426 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
/kube-centos/network/subnets/172.30.1.0-24
/kube-centos/network/subnets/172.30.82.0-24
/kube-centos/network/subnets/172.30.99.0-24
```
warning 应该不影响吧？

kube-proxy日志没有错误信息输出。
